
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Home from "./page";
import { Roboto, Montserrat, Barlow } from "next/font/google";

import Footers from "./components/footer";
const roboto = Barlow({
  subsets: ["latin"],
  weight: ["100", "500", "700","400","600"]
});

export const metadata = {
  title: "Equity-Bcdc",
  description: "Generated by create next app",
};

export default function RootLayout() {
  return (
    <html lang="en">
      <body className={roboto.className}>
       
        
        <Home/></body>
      
        
    </html>
  );
}
